[package]
name = "entrust-macros"
version = "0.1.0"
edition = "2018"


[lib]
proc-macro = true


[dependencies]
proc-macro2 = "^1.0.29"
quote = "^1.0.9"

[dependencies.syn]
version = "^1.0.77"
default-features = false
features = ["derive", "proc-macro"]


[profile.dev]
split-debuginfo = "unpacked"
