name: entrust

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore Rust cache
        uses: actions/cache@v2
        env:
          cache-name: rust
        with:
          path: ${{ github.workspace }}/target
          key: ${{ runner.os }}-${{ github.workflow }}-${{ github.job }}-${{ env.cache-name }}-${{ hashFiles('Cargo.lock') }}
          restore-keys: ${{ runner.os }}-${{ github.workflow }}-${{ github.job }}-${{ env.cache-name }}
      - name: Check
        run: cargo check --all-targets --all-features
      - name: Lint
        run: cargo clippy --all-targets --all-features
      - name: Format
        run: cargo fmt --all -- --check
